version: '3.3'
services:
  application:
    image: mirego_elixir_boilerplate:0.0.1
    container_name: mirego_elixir_boilerplate
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/mirego_elixir_boilerplate_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: mirego_elixir_boilerplate-postgres
    environment:
      - POSTGRES_DB=mirego_elixir_boilerplate_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - mirego_elixir_boilerplate_psql:/var/lib/postgresql/data
volumes:
  mirego_elixir_boilerplate_psql:
